### ISSUE TITLE
lint naming-conventions

### ISSUE THREAD

**Issue by moshloop** [flanksource/build-tools#12]
```yaml:
- glob: *.yml
  ignore:
    - .circleci/config.yml
    - .github/workflows/(.*)
    - .goreleaser.yml
    - mkdocs.yml
    - .git/(.*)
    - .golangci.yml
```

To replace https://github.com/flanksource/karina/blob/master/test/linter/main.go
